name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: |
          echo "example=value" >> $GITHUB_OUTPUT
        shell: bash
      - name: Use output
        run: echo "The output is ${{ steps.example.outputs.example }}"

      - name: Cleanup git config
        run: git config --unset-all http.https://github.com/.extraheader || true
      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: ~/.buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}}

      - name: Cache Buildozer directory
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: android debug
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
